# Generated by Django 5.0.6 on 2024-09-14 17:50

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='review',
            managers=[
                ('reviews', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='is_spam',
            field=models.BooleanField(default=False),
        ),
    ]
