# Generated by Django 5.0.6 on 2024-09-14 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_alter_review_managers_review_is_spam'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='review',
            managers=[
            ],
        ),
    ]
